import { chromium } from 'playwright';
const b = await chromium.launch({ args: ['--disable-background-timer-throttling'] });
const p = await b.newPage({ viewport: { width: 420, height: 740 } });
await p.addInitScript(() => { window.__NOAUDIO = true; });
await p.goto('http://localhost:5173/', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(1500);
await p.evaluate(() => { window.game.scene.getScenes(true).forEach(s=>{if(s.scene.key!=='DangerScene')s.scene.stop();}); window.game.scene.start('DangerScene'); });
await p.waitForTimeout(2000);
await p.evaluate(() => { const s=window.game.scene.getScene('DangerScene'); s.time.removeAllEvents(); s.invincibleUntil=1e12; s.player.x=1700; s.player.body.reset(1700,s.player.y); s.cameras.main.scrollX=1700-360;
  const bat=s.bats.create(2050, s.player.y-260, 'bat'); bat.setScale(120/bat.height); bat.setDepth(7); bat.alive=true; bat.play('bat-throw');
  s.spawnFireball(2000, s.player.y-260, s.player.x, s.player.y-40);
});
await p.waitForTimeout(250);
await p.screenshot({ path: 'tools/batshot.png' });
await b.close(); console.log('ok');
