import { chromium } from 'playwright';
const scene = process.argv[2] || 'GameScene';
const b = await chromium.launch({ args: ['--disable-background-timer-throttling','--disable-backgrounding-occluded-windows','--disable-renderer-backgrounding'] });
const p = await b.newPage({ viewport: { width: 450, height: 800 }, deviceScaleFactor: 2 });
const errs = [];
p.on('pageerror', e => errs.push('PAGEERROR: ' + e.message));
await p.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
await p.bringToFront();
await p.waitForTimeout(1400);
await p.evaluate((sc) => { window.__NOAUDIO = true; window.game.scene.getScenes(true).forEach(s => window.game.scene.stop(s.scene.key)); window.game.scene.start(sc); }, scene);
await p.waitForTimeout(900);
await p.evaluate((sc) => window.game.scene.getScene(sc).winLevel(), scene);
await p.waitForTimeout(700);
await p.mouse.click(225, 400);
await p.waitForTimeout(3000);
console.log('after tap active:', await p.evaluate(() => window.game.scene.getScenes(true).map(s => s.scene.key)));
console.log('errors:', errs.length ? errs.join('\n') : 'none');
await b.close();
